language: python
python:
#  - "3.3"
  - 2.7
#  - "2.6"

virtualenv:
  system_site_packages: true

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y python-scipy
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y cython
  - sudo apt-get install -y python-mpi4py
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install --allow-external Polygon2 --allow-unverified Polygon2 Polygon2; fi
  - pip install nose
  - pip install matplotlib
  - sudo sh hdf5_h5py_install.sh

script:  nosetests

notifications:
  email: false
